# Site settings
title: Quasar
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Quasar is the first native noSQL analytics engine that lets you 
  run SQL-based analytics on unstructured data.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://quasar-test.github.io/" # the base hostname & protocol for your site
twitter_username: quasar
github_username: quasar-analytics


collections:
  docs:
    output: true

# Build settings
markdown: kramdown
